# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

def discord(params)
  require 'net/http'
  require 'uri'
  require 'json'

  uri = URI.parse(params[:webhook_url])
  header = {'Content-Type': 'application/json'}
  body = {
    content: params[:message]
  }

  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = true
  request = Net::HTTP::Post.new(uri.request_uri, header)
  request.body = body.to_json
  response = http.request(request)

  UI.message("Discord response: #{response.body}")
end



platform :ios do
  desc "Description of what the lane does"
  lane :build do
    gym(scheme: "MultiCalendar")
  end

  lane :tests do
    run_tests(
      scheme: "MultiCalendar",
      clean: true,
      code_coverage: true,
    )
  end

  lane :discord do
    discord(
      webhook_url: "https://discord.com/api/webhooks/1411131335233372170/XTQhwu-jn5WUdCMdoFkHVRToe9VygKEuUfnPpLTyzzby5ic-4lhWL4PQP-HnsglzObg3x",
      message: "🚀 Deploy finalizado no TestFlight via Fastlane!"
    )
  end

end
